#!/bin/bash
if [ `whoami` == root ]; then
  echo "DONT run this script as root, or using sudo"
  exit
fi

echo ""
echo "*************************************"
echo "* Setting up ideal Unix environment *"
echo "*************************************"
echo ""

BASEDIR=$(cd "$(dirname "$0")"; pwd)

cd `dirname $0`

#
# Installing vim configurations
#
echo ""
echo "===>  Installing vim  <==="
echo "--->  Backing up any previous .vimrc"
cp $HOME/.vimrc $HOME/.vimrc.bak
echo "--->  Linking .vimrc"
ln -sf $BASEDIR/.vimrc $HOME/.vimrc
echo "--->  Linking .vim folder"
ln -sf $BASEDIR/vim $HOME/.vim

#
# Installing tmux configurations
#
echo ""
echo "===>  Installing tmux configurations <==="
echo "--->  Making backup of .tmux.conf"
cp $HOME/.tmux.conf $HOME/.tmux.conf.bak
echo "--->  Linking .tmux.conf"
ln -sf $BASEDIR/.tmux.conf $HOME/.tmux.conf

#
# Installing Git configurations
#
echo ""
echo "===>  Installing git configurations <==="
echo "--->  Making backup of .gitignore_global"
cp $HOME/.gitignore_global $HOME/.gitignore_global.bak
echo "--->  Making backup of .gitconfig"
cp $HOME/.gitconfig $HOME/.gitconfig.bak
echo "--->  Linking .gitconfig"
ln -sf $BASEDIR/.gitconfig $HOME/.gitconfig
echo "--->  Linking .gitignore_global"
ln -sf $BASEDIR/.gitignore_global $HOME/.gitignore_global


#
# Installing zsh configurations
#
echo ""
echo "===>  Installing zsh profile  <==="
echo "--->  Making backup of .zshrc"
cp $HOME/.zshrc $HOME/.zshrc.bak
echo "--->  Linking .zshrc"
ln -sf $BASEDIR/.zshrc $HOME/.zshrc
echo "--->  Linking .thmsmlr.zsh-theme"
ln -sf $BASEDIR/.thmsmlr.zsh-theme $HOME/.thmsmlr.zsh-theme

source ~/.zshrc


echo ""
echo "====  Successfully installed Thomas's environment  ===="
