#!/bin/bash
set -e

if [ `whoami` == root ]; then
  echo "DONT run this script as root, or using sudo"
  exit
fi

echo ""
echo "*************************************"
echo "* Setting up ideal Unix environment *"
echo "*************************************"
echo ""

BASEDIR=$(cd "$(dirname "$0")"; pwd)

cd `dirname $0`

#
# Installing vim configurations
#
echo ""
echo "===>  Installing vim  <==="
if [ -f $HOME/.vimrc ]; then
  echo "--->  Backing up any previous .vimrc"
  cp $HOME/.vimrc $HOME/.vimrc.bak
fi
echo "--->  Linking .vimrc"
ln -sf $BASEDIR/.vimrc $HOME/.vimrc
echo "--->  Linking .vim folder"
ln -sf $BASEDIR/vim $HOME/.vim

#
# Installing tmux configurations
#
echo ""
echo "===>  Installing tmux configurations <==="
if [ -f $HOME/.tmux.conf ]; then
  echo "--->  Making backup of .tmux.conf"
  cp $HOME/.tmux.conf $HOME/.tmux.conf.bak
fi
echo "--->  Linking .tmux.conf"
ln -sf $BASEDIR/.tmux.conf $HOME/.tmux.conf

#
# Installing Git configurations
#
echo ""
echo "===>  Installing git configurations <==="
if [ -f $HOME/.gitignore_global ]; then
  echo "--->  Making backup of .gitignore_global"
  cp $HOME/.gitignore_global $HOME/.gitignore_global.bak
fi
if [ -f $HOME/.gitconfig ]; then
  echo "--->  Making backup of .gitconfig"
  cp $HOME/.gitconfig $HOME/.gitconfig.bak
fi
echo "--->  Linking .gitconfig"
ln -sf $BASEDIR/.gitconfig $HOME/.gitconfig
echo "--->  Linking .gitignore_global"
ln -sf $BASEDIR/.gitignore_global $HOME/.gitignore_global


#
# Installing zsh configurations
#
echo ""
echo "===>  Installing zsh profile  <==="
if [ -f $HOME/.zshrc ]; then
  echo "--->  Making backup of .zshrc"
  cp $HOME/.zshrc $HOME/.zshrc.bak
fi
echo "--->  Linking .zshrc"
ln -sf $BASEDIR/.zshrc $HOME/.zshrc
echo "--->  Linking .thmsmlr.zsh-theme"
ln -sf $BASEDIR/.thmsmlr.zsh-theme $HOME/.thmsmlr.zsh-theme
echo "--->  Creating local configurations"
touch $HOME/.zshrc.local

#
# Installing Python 
#
echo ""
echo "===>  Installing Python profile  <==="
if [ -f $HOME/.pythonrc ]; then
  echo "--->  Making backup of .pythonrc"
  cp $HOME/.pythonrc $HOME/.pythonrc.bak
fi
echo "--->  Linking .pythonrc"
ln -sf $BASEDIR/.pythonrc $HOME/.pythonrc


echo ""
echo "====  Successfully installed Thomas's environment  ===="
